[Intermittent][BugFix] Fix intermittent bugs.
info: running `cargo nextest run --no-fail-fast --failure-output final --status-level=fail --no-default-features --features async-std-scheduler` on rx-rust (1/4)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.03s
────────────
 Nextest run ID 3e86f9a8-569a-4cdc-ba19-f5131cd489e2 with nextest profile: default
    Starting 1288 tests across 84 binaries
   LEAK-FAIL [   1.208s] rx-rust::scheduler test_schedule_recursively_small_delay
────────────
     Summary [   4.410s] 1288 tests run: 1287 passed, 1 failed (1 due to being leaky), 0 skipped
   LEAK-FAIL [   1.208s] rx-rust::scheduler test_schedule_recursively_small_delay
  stdout ───

    running 1 test
    test test_schedule_recursively_small_delay ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 8 filtered out; finished in 0.20s

    (test failed: exited with code 0, but leaked handles)

error: test run failed
error: process didn't exit successfully: `/Users/yawang/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo nextest run --no-fail-fast --failure-output final --status-level=fail --manifest-path Cargo.toml --no-default-features --features async-std-scheduler` (exit status: 100)
cargo hack --each-feature --exclude-all-features --exclude-no-default-feature  4.33s user 3.25s system 160% cpu 4.722 total
yawang@Yannis-MacBook-Pro-2024 rx-rust %